### ISSUE TITLE
couple questions

### ISSUE THREAD

**Issue by abalib** [intel/cNVMe#39]
What is the letter 'c' in cNVMe for? 

Is this simulation of a legit NVMe device?  What is the purpose of your code?

How do I go about putting a Linux kernel driver on top?  Can I for example create a /dev/nvme0 device using your source and fake the kernel to believe that it's talking to an actual nvme device?

I am interested in using an FPGA to make an NVMe target emulator.  I thought your code may be good starting point.

**Comment by csm10495** [comment]
It was for "Charlie" which is my name. 

It's a simulation of a 'fake' NVMe device, abstracting out all hardware to focus on the protocol. It was a learning experience to better understand how a controller internally could handle commands after abstracting hardware. After that it taught me some potential issues with driver/controller interaction.

I'm not entirely sure how one would go about faking a /dev node from it, though it wouldn't surprise me if possible. Though it may very well be possible to do a library build or something like that then have the driver load it or communicate with a service of some sort with the service using the lib.

Unfortunately I don't really have much time to work at this at the moment.

**Comment by abalib** [comment]
got it. good stuff.  thank you
